/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aula04MVC.ProjetoVendas.DTO;

import Aula04MVC.ProjetoVendas.Util.DataUtil;
import Aula04MVC.ProjetoVendas.Util.Encription;
import Aula04MVC.ProjetoVendas.Util.JavaMailApp;
import Aula04MVC.ProjetoVendas.Util.Sincronizacao;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import Aula04MVC.ProjetoVendas.persistence.InjecaoDependencia;
import Aula04MVC.ProjetoVendas.persistence.JSON;
import Aula04MVC.ProjetoVendas.persistence.Persistencia;
import Aula04MVC.ProjetoVendas.persistence.XML;

/**
 *
 * @author rodriguh
 */
public class main extends javax.swing.JFrame {

    private InjecaoDependencia inj;
    private Persistencia persistencia;

    private List<Cliente> clientes;
    private List<Venda> vendas;
    private List<Vendedor> vendedores;
    private List<Produto> produtos;
    private Usuario loggedUser = null;

    private int randomNum;
    private List<ItemVenda> itens;

    public main() {
        initComponents();
        initJComponents();
    }
    
    private void initJComponents(){
        tipoPersistencia.setSelected(lXML.getModel(), true);
        tipoUsuario.setSelected(lVendedor.getModel(), true);
        lError.setVisible(false);
        cvError.setVisible(false);
        rvValorVenda.setVisible(false);
        rvValorItem.setVisible(false);
        ccError.setVisible(false);
        cError.setVisible(false);
        cpError.setVisible(false);
    }
    
    private void setPersistenceModel() {
        if (lXML.isSelected()) {
            persistencia = new XML();
        } else {
            persistencia = new JSON();
        }
        inj = new InjecaoDependencia(persistencia);
        try {
            initLists();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
    }

    private void initLists() throws FileNotFoundException {
        clientes = inj.importar(new Cliente());
        vendas = inj.importar(new Venda());
        vendedores = inj.importar(new Vendedor());
        produtos = inj.importar(new Produto());
        itens = new ArrayList<>();

    }

    private void changePanel(JPanel panel) {
        painelPai.removeAll();
        painelPai.add(panel);
        painelPai.repaint();
        painelPai.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoPersistencia = new javax.swing.ButtonGroup();
        tipoUsuario = new javax.swing.ButtonGroup();
        painelPai = new javax.swing.JPanel();
        telaLogin = new javax.swing.JPanel();
        lUsuario = new javax.swing.JTextField();
        lXML = new javax.swing.JRadioButton();
        lJSON = new javax.swing.JRadioButton();
        lCliente = new javax.swing.JRadioButton();
        lVendedor = new javax.swing.JRadioButton();
        lLogin = new javax.swing.JButton();
        lError = new javax.swing.JLabel();
        lCadastrar = new javax.swing.JButton();
        lSenha = new javax.swing.JPasswordField();
        telaCadastroVendedor = new javax.swing.JPanel();
        cvNome = new javax.swing.JTextField();
        cvUsuario = new javax.swing.JTextField();
        cvEmail = new javax.swing.JTextField();
        cvId = new javax.swing.JTextField();
        cvError = new javax.swing.JLabel();
        cvCadastrar = new javax.swing.JButton();
        cvVoltar = new javax.swing.JButton();
        cvSenha = new javax.swing.JPasswordField();
        telaRealizaVenda = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        rvClientBox = new javax.swing.JComboBox<>();
        rvSelectClient = new javax.swing.JLabel();
        rvProductBox = new javax.swing.JComboBox<>();
        rvOkProduct = new javax.swing.JButton();
        mvSelectProduct = new javax.swing.JLabel();
        rvQtd = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        rvFinalizarCompra = new javax.swing.JButton();
        rvDataPagamento = new javax.swing.JTextField();
        rvDataVencimento = new javax.swing.JTextField();
        rvVoltar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        rvValorItem = new javax.swing.JLabel();
        rvValorVenda = new javax.swing.JLabel();
        rvID = new javax.swing.JTextField();
        telaMainCliente = new javax.swing.JPanel();
        mcScrollPanel = new javax.swing.JScrollPane();
        mcTable = new javax.swing.JTable();
        mcVoltar = new javax.swing.JButton();
        mcComprasBox = new javax.swing.JComboBox<>();
        mcOk = new javax.swing.JButton();
        telaCadastroCliente = new javax.swing.JPanel();
        ccError = new javax.swing.JLabel();
        ccNome = new javax.swing.JTextField();
        ccCPF = new javax.swing.JTextField();
        ccEmail = new javax.swing.JTextField();
        ccUsuario = new javax.swing.JTextField();
        ccRG = new javax.swing.JTextField();
        ccFone = new javax.swing.JTextField();
        ccEndereco = new javax.swing.JTextField();
        ccNumero = new javax.swing.JTextField();
        ccBairro = new javax.swing.JTextField();
        ccCidade = new javax.swing.JTextField();
        ccId = new javax.swing.JTextField();
        ccEstado = new javax.swing.JTextField();
        ccCadastrar = new javax.swing.JButton();
        ccVoltar = new javax.swing.JButton();
        ccSenha = new javax.swing.JPasswordField();
        telaCodigo = new javax.swing.JPanel();
        cCodigo = new javax.swing.JTextField();
        cIr = new javax.swing.JButton();
        cVoltar = new javax.swing.JButton();
        cError = new javax.swing.JLabel();
        telaEditaVenda = new javax.swing.JPanel();
        evVoltar = new javax.swing.JButton();
        evSalvarVenda = new javax.swing.JButton();
        evQuantidadeEditar = new javax.swing.JTextField();
        evSalvarItem = new javax.swing.JButton();
        evDataPagamento = new javax.swing.JTextField();
        evDataVencimento = new javax.swing.JTextField();
        evOkEditar = new javax.swing.JButton();
        evExcluirVenda = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        evAddItemBox = new javax.swing.JComboBox<>();
        evOkAddItem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        evQuantidadeAddItem = new javax.swing.JTextField();
        evItemVendaBox = new javax.swing.JComboBox<>();
        evExcluirItem = new javax.swing.JButton();
        telaMainVendedor = new javax.swing.JPanel();
        mvCriarVenda = new javax.swing.JButton();
        mvSelecionaVenda = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        mvEditarVenda = new javax.swing.JLabel();
        mvVendaBox = new javax.swing.JComboBox<>();
        jSeparator8 = new javax.swing.JSeparator();
        mvCadastrarProduto = new javax.swing.JButton();
        mvSair = new javax.swing.JButton();
        mvSincronizar = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        telaCadastroProduto = new javax.swing.JPanel();
        cpId = new javax.swing.JTextField();
        cpDescricao = new javax.swing.JTextField();
        cpValor = new javax.swing.JTextField();
        cpEstoque = new javax.swing.JTextField();
        cpCadastrar = new javax.swing.JButton();
        cpVoltar = new javax.swing.JButton();
        cpError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPai.setLayout(new java.awt.CardLayout());

        lUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lUsuario.setText("USUÁRIO");

        tipoPersistencia.add(lXML);
        lXML.setText("XML");

        tipoPersistencia.add(lJSON);
        lJSON.setText("JSON");

        tipoUsuario.add(lCliente);
        lCliente.setText("CLIENTE");

        tipoUsuario.add(lVendedor);
        lVendedor.setText("VENDEDOR");

        lLogin.setText("LOGIN");
        lLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lLoginActionPerformed(evt);
            }
        });

        lError.setForeground(new java.awt.Color(255, 0, 0));
        lError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lError.setText("USUÁRIO OU SENHA INCORRETOS");

        lCadastrar.setText("CADASTRAR");
        lCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lCadastrarActionPerformed(evt);
            }
        });

        lSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lSenha.setText("jdField1");

        javax.swing.GroupLayout telaLoginLayout = new javax.swing.GroupLayout(telaLogin);
        telaLogin.setLayout(telaLoginLayout);
        telaLoginLayout.setHorizontalGroup(
            telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaLoginLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, telaLoginLayout.createSequentialGroup()
                        .addComponent(lCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lVendedor))
                    .addComponent(lUsuario)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, telaLoginLayout.createSequentialGroup()
                        .addComponent(lXML)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lJSON))
                    .addGroup(telaLoginLayout.createSequentialGroup()
                        .addComponent(lCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(lLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lSenha))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        telaLoginLayout.setVerticalGroup(
            telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaLoginLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lXML)
                    .addComponent(lJSON))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCliente)
                    .addComponent(lVendedor))
                .addGap(18, 18, 18)
                .addComponent(lError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lLogin)
                    .addComponent(lCadastrar))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        painelPai.add(telaLogin, "card2");

        cvNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cvNome.setText("NOME");

        cvUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cvUsuario.setText("USUARIO");

        cvEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cvEmail.setText("EMAIL");

        cvId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cvId.setText("ID");

        cvError.setForeground(new java.awt.Color(255, 0, 0));
        cvError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cvError.setText("VENDEDOR JÁ CADASTRADO");

        cvCadastrar.setText("CADASTRAR");
        cvCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvCadastrarActionPerformed(evt);
            }
        });

        cvVoltar.setText("VOLTAR");
        cvVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvVoltarActionPerformed(evt);
            }
        });

        cvSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cvSenha.setText("jPasswordField1");

        javax.swing.GroupLayout telaCadastroVendedorLayout = new javax.swing.GroupLayout(telaCadastroVendedor);
        telaCadastroVendedor.setLayout(telaCadastroVendedorLayout);
        telaCadastroVendedorLayout.setHorizontalGroup(
            telaCadastroVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroVendedorLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(telaCadastroVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(telaCadastroVendedorLayout.createSequentialGroup()
                        .addComponent(cvVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cvCadastrar))
                    .addComponent(cvId, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(cvEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(cvUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(cvNome)
                    .addComponent(cvError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cvSenha))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        telaCadastroVendedorLayout.setVerticalGroup(
            telaCadastroVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCadastroVendedorLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(cvError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cvId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cvNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cvUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cvEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(cvSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaCadastroVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvCadastrar)
                    .addComponent(cvVoltar))
                .addGap(54, 54, 54))
        );

        painelPai.add(telaCadastroVendedor, "card3");

        rvClientBox.setModel(new javax.swing.DefaultComboBoxModel<>(new Cliente[]{}));

        rvSelectClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rvSelectClient.setText("SELECIONE O CLIENTE");

        rvProductBox.setModel(new javax.swing.DefaultComboBoxModel<>(new Produto[]{}));

        rvOkProduct.setText("ADICIONAR PRODUTO");
        rvOkProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rvOkProductActionPerformed(evt);
            }
        });

        mvSelectProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mvSelectProduct.setText("SELECIONE O PRODUTO");

        rvQtd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rvQtd.setText("QTD");

        rvFinalizarCompra.setText("FINALIZAR COMPRA");
        rvFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rvFinalizarCompraActionPerformed(evt);
            }
        });

        rvDataPagamento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rvDataPagamento.setText("DATA PAGAMENTO");

        rvDataVencimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rvDataVencimento.setText("DATA VENCIMENTO");

        rvVoltar.setText("VOLTAR");

        rvValorItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rvValorItem.setText("VALOR PRODUTO");

        rvValorVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rvValorVenda.setText("VALOR TOTAL DA VENDA");

        rvID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rvID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rvID.setText("ID");

        javax.swing.GroupLayout telaRealizaVendaLayout = new javax.swing.GroupLayout(telaRealizaVenda);
        telaRealizaVenda.setLayout(telaRealizaVendaLayout);
        telaRealizaVendaLayout.setHorizontalGroup(
            telaRealizaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaRealizaVendaLayout.createSequentialGroup()
                .addGroup(telaRealizaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(telaRealizaVendaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rvID, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaRealizaVendaLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(telaRealizaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rvValorVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rvValorItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(telaRealizaVendaLayout.createSequentialGroup()
                                .addComponent(rvFinalizarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rvVoltar))
                            .addComponent(rvOkProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addComponent(mvSelectProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, telaRealizaVendaLayout.createSequentialGroup()
                                .addComponent(rvProductBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rvQtd))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, telaRealizaVendaLayout.createSequentialGroup()
                                .addGroup(telaRealizaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rvSelectClient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(rvClientBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(telaRealizaVendaLayout.createSequentialGroup()
                                        .addGroup(telaRealizaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rvDataPagamento)
                                            .addComponent(rvDataVencimento))
                                        .addGap(65, 65, 65)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(173, 173, 173))
        );
        telaRealizaVendaLayout.setVerticalGroup(
            telaRealizaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaRealizaVendaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rvSelectClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rvClientBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mvSelectProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaRealizaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rvProductBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rvQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rvOkProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rvValorItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rvValorVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaRealizaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(telaRealizaVendaLayout.createSequentialGroup()
                        .addComponent(rvDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rvDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rvID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaRealizaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rvVoltar)
                    .addComponent(rvFinalizarCompra))
                .addGap(26, 26, 26))
        );

        painelPai.add(telaRealizaVenda, "card4");

        mcTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Vendedor", "Title 3", "Title 4", "Title 5"
            }
        ));
        mcScrollPanel.setViewportView(mcTable);

        mcVoltar.setText("VOLTAR");
        mcVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcVoltarActionPerformed(evt);
            }
        });

        mcComprasBox.setModel(new javax.swing.DefaultComboBoxModel<>(new Venda[]{}));
        mcComprasBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcComprasBoxActionPerformed(evt);
            }
        });

        mcOk.setText("OK");

        javax.swing.GroupLayout telaMainClienteLayout = new javax.swing.GroupLayout(telaMainCliente);
        telaMainCliente.setLayout(telaMainClienteLayout);
        telaMainClienteLayout.setHorizontalGroup(
            telaMainClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mcScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaMainClienteLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(mcComprasBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mcOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mcVoltar)
                .addGap(27, 27, 27))
        );
        telaMainClienteLayout.setVerticalGroup(
            telaMainClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaMainClienteLayout.createSequentialGroup()
                .addComponent(mcScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(telaMainClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mcVoltar)
                    .addComponent(mcComprasBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mcOk))
                .addGap(26, 26, 26))
        );

        painelPai.add(telaMainCliente, "card5");

        ccError.setForeground(new java.awt.Color(255, 0, 0));
        ccError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ccError.setText("JÁ CADASTRADO");

        ccNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccNome.setText("NOME");

        ccCPF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccCPF.setText("CPF");

        ccEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccEmail.setText("EMAIL");

        ccUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccUsuario.setText("USUÁRIO");

        ccRG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccRG.setText("RG");

        ccFone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccFone.setText("FONE");

        ccEndereco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccEndereco.setText("ENDEREÇO");

        ccNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccNumero.setText("Nº");

        ccBairro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccBairro.setText("BAIRRO");

        ccCidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccCidade.setText("CIDADE");

        ccId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccId.setText("ID");

        ccEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccEstado.setText("ESTADO");

        ccCadastrar.setText("CADASTRAR");
        ccCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccCadastrarActionPerformed(evt);
            }
        });

        ccVoltar.setText("VOLTAR");
        ccVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccVoltarActionPerformed(evt);
            }
        });

        ccSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccSenha.setText("jPasswordField1");

        javax.swing.GroupLayout telaCadastroClienteLayout = new javax.swing.GroupLayout(telaCadastroCliente);
        telaCadastroCliente.setLayout(telaCadastroClienteLayout);
        telaCadastroClienteLayout.setHorizontalGroup(
            telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroClienteLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCadastroClienteLayout.createSequentialGroup()
                        .addComponent(ccError, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCadastroClienteLayout.createSequentialGroup()
                        .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ccVoltar)
                            .addGroup(telaCadastroClienteLayout.createSequentialGroup()
                                .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ccId, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(ccUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(ccEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(ccRG, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(ccCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(ccNome, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(ccSenha))
                                .addGap(67, 67, 67)
                                .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ccFone, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(ccEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(ccBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(ccCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(ccNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(ccEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(ccCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(97, 97, 97))))
        );
        telaCadastroClienteLayout.setVerticalGroup(
            telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroClienteLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ccError)
                .addGap(18, 18, 18)
                .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaCadastroClienteLayout.createSequentialGroup()
                        .addComponent(ccCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ccRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaCadastroClienteLayout.createSequentialGroup()
                        .addComponent(ccEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ccBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaCadastroClienteLayout.createSequentialGroup()
                        .addComponent(ccId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ccUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaCadastroClienteLayout.createSequentialGroup()
                        .addComponent(ccNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ccCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ccEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ccCadastrar)
                    .addComponent(ccSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ccVoltar)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        painelPai.add(telaCadastroCliente, "card6");

        cCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cCodigo.setText("INSIRA SEU CÓDIGO AQUI");

        cIr.setText("IR");
        cIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cIrActionPerformed(evt);
            }
        });

        cVoltar.setText("VOLTAR");
        cVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cVoltarActionPerformed(evt);
            }
        });

        cError.setForeground(new java.awt.Color(255, 0, 0));
        cError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cError.setText("CÓDIGO INCORRETO");

        javax.swing.GroupLayout telaCodigoLayout = new javax.swing.GroupLayout(telaCodigo);
        telaCodigo.setLayout(telaCodigoLayout);
        telaCodigoLayout.setHorizontalGroup(
            telaCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCodigoLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(telaCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cCodigo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCodigoLayout.createSequentialGroup()
                        .addComponent(cVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(cIr, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(185, 185, 185))
        );
        telaCodigoLayout.setVerticalGroup(
            telaCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCodigoLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(cError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(telaCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cIr)
                    .addComponent(cVoltar))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        painelPai.add(telaCodigo, "card7");

        evVoltar.setText("VOLTAR");
        evVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evVoltarActionPerformed(evt);
            }
        });

        evSalvarVenda.setText("SALVAR VENDA");
        evSalvarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evSalvarVendaActionPerformed(evt);
            }
        });

        evQuantidadeEditar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        evQuantidadeEditar.setText("QTD");

        evSalvarItem.setText("SALVAR ITEM");
        evSalvarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evSalvarItemActionPerformed(evt);
            }
        });

        evDataPagamento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        evDataPagamento.setText("DATA PAGAMENTO");

        evDataVencimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        evDataVencimento.setText("DATA VENCIMENTO");

        evOkEditar.setText("OK");
        evOkEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evOkEditarActionPerformed(evt);
            }
        });

        evExcluirVenda.setText("EXCLUIR VENDA");
        evExcluirVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evExcluirVendaActionPerformed(evt);
            }
        });

        evAddItemBox.setModel(new javax.swing.DefaultComboBoxModel<>(new Produto[] {}));

        evOkAddItem.setText("OK");
        evOkAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evOkAddItemActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADICIONAR ITEM");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EDITAR ITEM");

        evQuantidadeAddItem.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        evQuantidadeAddItem.setText("QUANTIDADE");

        evItemVendaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new ItemVenda[]{}));

        evExcluirItem.setText("EXCLUIR ITEM");
        evExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evExcluirItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaEditaVendaLayout = new javax.swing.GroupLayout(telaEditaVenda);
        telaEditaVenda.setLayout(telaEditaVendaLayout);
        telaEditaVendaLayout.setHorizontalGroup(
            telaEditaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaEditaVendaLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addGroup(telaEditaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(evDataPagamento)
                    .addComponent(jSeparator4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(telaEditaVendaLayout.createSequentialGroup()
                        .addComponent(evQuantidadeAddItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(evOkAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, telaEditaVendaLayout.createSequentialGroup()
                        .addComponent(evSalvarVenda)
                        .addGap(18, 18, 18)
                        .addComponent(evVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(evExcluirVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6)
                    .addComponent(evDataVencimento)
                    .addComponent(evAddItemBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(telaEditaVendaLayout.createSequentialGroup()
                        .addGroup(telaEditaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(evExcluirItem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(evItemVendaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(telaEditaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaEditaVendaLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(evQuantidadeEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(evOkEditar))
                            .addComponent(evSalvarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(157, 157, 157))
        );
        telaEditaVendaLayout.setVerticalGroup(
            telaEditaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaEditaVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(evDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(evDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(evAddItemBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaEditaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evOkAddItem)
                    .addComponent(evQuantidadeAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(telaEditaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evOkEditar)
                    .addComponent(evItemVendaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(evQuantidadeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaEditaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evSalvarItem)
                    .addComponent(evExcluirItem))
                .addGap(4, 4, 4)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(evExcluirVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaEditaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaEditaVendaLayout.createSequentialGroup()
                        .addComponent(evSalvarVenda)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(evVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        painelPai.add(telaEditaVenda, "card8");

        mvCriarVenda.setText("CRIAR NOVA VENDA");
        mvCriarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvCriarVendaActionPerformed(evt);
            }
        });

        mvSelecionaVenda.setText("OK");
        mvSelecionaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvSelecionaVendaActionPerformed(evt);
            }
        });

        mvEditarVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mvEditarVenda.setText("EDITAR VENDA");

        mvCadastrarProduto.setText("CADASTRAR PRODUTO");
        mvCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvCadastrarProdutoActionPerformed(evt);
            }
        });

        mvSair.setText("SAIR");
        mvSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvSairActionPerformed(evt);
            }
        });

        mvSincronizar.setText("SINCRONIZAR PERSISTENCIAS");
        mvSincronizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvSincronizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaMainVendedorLayout = new javax.swing.GroupLayout(telaMainVendedor);
        telaMainVendedor.setLayout(telaMainVendedorLayout);
        telaMainVendedorLayout.setHorizontalGroup(
            telaMainVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaMainVendedorLayout.createSequentialGroup()
                .addGroup(telaMainVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, telaMainVendedorLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(mvCriarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaMainVendedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(telaMainVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mvSair, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator7)
                            .addComponent(mvEditarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mvCadastrarProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(telaMainVendedorLayout.createSequentialGroup()
                                .addComponent(mvVendaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mvSelecionaVenda))
                            .addComponent(jSeparator9)
                            .addComponent(mvSincronizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        telaMainVendedorLayout.setVerticalGroup(
            telaMainVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaMainVendedorLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(mvCriarVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mvEditarVenda)
                .addGap(18, 18, 18)
                .addGroup(telaMainVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mvVendaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mvSelecionaVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mvCadastrarProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mvSincronizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(mvSair)
                .addGap(31, 31, 31))
        );

        painelPai.add(telaMainVendedor, "card9");

        cpId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpId.setText("ID");

        cpDescricao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpDescricao.setText("DESCRIÇÃO");

        cpValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpValor.setText("VALOR");

        cpEstoque.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpEstoque.setText("ESTOQUE");

        cpCadastrar.setText("CADASTRAR");
        cpCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpCadastrarActionPerformed(evt);
            }
        });

        cpVoltar.setText("VOLTAR");
        cpVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpVoltarActionPerformed(evt);
            }
        });

        cpError.setForeground(new java.awt.Color(255, 0, 0));
        cpError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cpError.setText("ID JÁ CADASTRADO");

        javax.swing.GroupLayout telaCadastroProdutoLayout = new javax.swing.GroupLayout(telaCadastroProduto);
        telaCadastroProduto.setLayout(telaCadastroProdutoLayout);
        telaCadastroProdutoLayout.setHorizontalGroup(
            telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCadastroProdutoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cpVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cpCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addGap(225, 225, 225))
            .addGroup(telaCadastroProdutoLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cpEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(cpValor, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(cpDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(cpId, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(cpError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        telaCadastroProdutoLayout.setVerticalGroup(
            telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroProdutoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(cpError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cpCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpVoltar)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        painelPai.add(telaCadastroProduto, "card10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ccCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccCadastrarActionPerformed
        ccError.setVisible(false);
        for (Cliente c : clientes) {
            if (c.getID() == Integer.parseInt(ccId.getText())) {
                ccError.setText("ID JÁ CADASTRADO");
                ccError.setVisible(true);
                ccId.setText("ID");
            }
            if (c.getUsuario().equals(ccUsuario.getText())) {
                ccError.setText("USUÁRIO JÁ CADASTRADO");
                ccError.setVisible(true);
                ccUsuario.setText("USUARIO");
            }
        }
        if (!ccError.isVisible()) {
            randomNum = ThreadLocalRandom.current().nextInt(10000, 99999);
            JavaMailApp.enviar(ccEmail.getText(), "Código de verificação", "Insira o código " + randomNum + " para confirmar o cadastro.");
            changePanel(telaCodigo);
        }
    }//GEN-LAST:event_ccCadastrarActionPerformed

    private void ccVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccVoltarActionPerformed
        changePanel(telaLogin);
    }//GEN-LAST:event_ccVoltarActionPerformed

    private void rvOkProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rvOkProductActionPerformed
        Produto p = (Produto) rvProductBox.getSelectedItem();
        ItemVenda e = new ItemVenda();
        e.setDescricao(p.getDescricao());
        e.setEstoque(p.getEstoque());
        e.setId(p.getId());
        e.setValor(p.getValor());
        e.setQuantidade(Integer.parseInt(rvQtd.getText()));
        rvValorItem.setText("Valor produto " + e.getDescricao() + ": R$ " + String.valueOf(e.valorItem()));
        rvValorItem.setVisible(true);
        itens.add(e);
    }//GEN-LAST:event_rvOkProductActionPerformed

    private void rvFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rvFinalizarCompraActionPerformed
        Venda v = null;
        Cliente c = (Cliente)rvClientBox.getSelectedItem();
        try {
            v = new Venda();
            Vendedor vendedor = new Vendedor();
            vendedor.setID(loggedUser.getID());
            vendedor.setNome(loggedUser.getNome());
            vendedor.setSenha(loggedUser.getSenha());
            vendedor.setUsuario(loggedUser.getUsuario());
            v.setProdutos(itens);
            v.setCliente(c);
            v.setData(new Date());
            v.setDataPagamento(DataUtil.StringParaData(rvDataPagamento.getText()));
            v.setDataVencimento(DataUtil.StringParaData(rvDataVencimento.getText()));
            v.setId_venda(Integer.parseInt(rvID.getText()));
            v.setVendedor(vendedor);
            rvValorVenda.setText(String.valueOf(v.valorVenda()));
            rvValorVenda.setVisible(true);
            
        } catch (ParseException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (v != null){
            vendas.add(v);
            inj.exportarVenda(vendas);
            mvVendaBox.addItem(v);
            rvValorItem.setText("VENDA FINALIZADA!");
            rvValorItem.setForeground(Color.GREEN);
            JavaMailApp.enviar(c.getEmail(), "Compra realizada com sucesso", "Caro, "+ c.getNome()+". Sua compra de "+rvValorVenda.getText()+" reais foi realizada com sucesso!");
            try {
                Thread.sleep(5000);
            } catch (InterruptedException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
            changePanel(telaMainVendedor);
        }
    }//GEN-LAST:event_rvFinalizarCompraActionPerformed

    private void lLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lLoginActionPerformed
        setPersistenceModel();
        boolean flag = false;
        if (lVendedor.isSelected()) {
            for (Vendedor v : vendedores) {
                if (v.getUsuario().equals(lUsuario.getText()) && v.getSenha().equals(Encription.sha1(new String(lSenha.getPassword())))) {
                    loggedUser = v;
                    flag = true;
                    break;
                }
            }
        } else {
            for (Cliente c : clientes) {
                if (c.getUsuario().equals(lUsuario.getText()) && c.getSenha().equals(Encription.sha1(new String(lSenha.getPassword())))) {
                    loggedUser = c;
                    break;
                }
            }
        }
        if (loggedUser != null) {
            if (flag) {
                for (Venda v : vendas) {
                    mvVendaBox.addItem(v);
                }
                changePanel(telaMainVendedor);

            } else {
                changePanel(telaMainCliente);
            }
        } else {
            lError.setVisible(true);
        }

    }//GEN-LAST:event_lLoginActionPerformed

    private void lCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lCadastrarActionPerformed
        setPersistenceModel();
        if (lVendedor.isSelected()) {
            changePanel(telaCadastroVendedor);
        } else {
            changePanel(telaCadastroCliente);
        }
    }//GEN-LAST:event_lCadastrarActionPerformed

    private void cvCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvCadastrarActionPerformed
        cvError.setVisible(false);
        for (Vendedor v : vendedores) {
            if (v.getID() == Integer.parseInt(cvId.getText())) {
                cvError.setText("ID JÁ CADASTRADA");
                cvError.setVisible(true);
                cvId.setText("ID");
            }
            if (v.getUsuario().equals(cvUsuario.getText())) {
                cvError.setText("USUARIO JÁ CADASTRADO");
                cvError.setVisible(true);
                cvUsuario.setText("USUARIO");
            }
        }
        if (!cvError.isVisible()) {
            Vendedor v = new Vendedor();
            v.setID(Integer.parseInt(cvId.getText()));
            v.setNome(cvNome.getText());
            v.setSenha(Encription.sha1(new String(cvSenha.getPassword())));
            v.setUsuario(cvUsuario.getText());
            vendedores.add(v);
            inj.exportarVendedor(vendedores);
            changePanel(telaLogin);
        }
    }//GEN-LAST:event_cvCadastrarActionPerformed

    private void cvVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvVoltarActionPerformed
        changePanel(telaLogin);
    }//GEN-LAST:event_cvVoltarActionPerformed

    private void cpVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpVoltarActionPerformed
        changePanel(telaMainVendedor);
    }//GEN-LAST:event_cpVoltarActionPerformed

    private void cpCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpCadastrarActionPerformed
        cpError.setVisible(false);
        for (Produto p : produtos) {
            if (Integer.parseInt(cpId.getText()) == p.getId()) {
                cpError.setVisible(true);
                break;
            }
        }
        if (!cpError.isVisible()) {
            Produto p = new Produto();
            p.setDescricao(cpDescricao.getText());
            p.setEstoque(Integer.parseInt(cpEstoque.getText()));
            p.setId(Integer.parseInt(cpId.getText()));
            p.setValor(Float.parseFloat(cpValor.getText()));
            produtos.add(p);
            inj.exportarProduto(produtos);
        }

    }//GEN-LAST:event_cpCadastrarActionPerformed

    private void mvCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvCadastrarProdutoActionPerformed
        changePanel(telaCadastroProduto);
    }//GEN-LAST:event_mvCadastrarProdutoActionPerformed

    private void mvSelecionaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvSelecionaVendaActionPerformed
        Venda v = (Venda) mvVendaBox.getSelectedItem();
        for (Produto p : produtos) {
            evAddItemBox.addItem(p);
        }
        evDataPagamento.setText(DataUtil.DataForStringPadrao(v.getDataPagamento()));
        evDataVencimento.setText(DataUtil.DataForStringPadrao(v.getDataVencimento()));
        for (ItemVenda iv : v.getProdutos()) {
            evItemVendaBox.addItem(iv);
        }
        changePanel(telaEditaVenda);
    }//GEN-LAST:event_mvSelecionaVendaActionPerformed

    private void mvCriarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvCriarVendaActionPerformed
        for (Cliente c : clientes) {
            rvClientBox.addItem(c);
        }
        for (Produto p : produtos) {
            rvProductBox.addItem(p);
        }

        changePanel(telaRealizaVenda);
    }//GEN-LAST:event_mvCriarVendaActionPerformed

    private void evOkAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evOkAddItemActionPerformed
        Produto p = (Produto) evAddItemBox.getSelectedItem();
        ItemVenda e = new ItemVenda();
        e.setDescricao(p.getDescricao());
        e.setEstoque(p.getEstoque());
        e.setId(p.getId());
        e.setValor(p.getValor());
        e.setQuantidade(Integer.parseInt(evQuantidadeAddItem.getText()));
        vendas.get(mvVendaBox.getSelectedIndex()).getProdutos().add(e);
        inj.exportarVenda(vendas);
    }//GEN-LAST:event_evOkAddItemActionPerformed

    private void evExcluirVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evExcluirVendaActionPerformed
        vendas.remove((Venda) mvVendaBox.getSelectedItem());
        inj.exportarVenda(vendas);
        mvVendaBox.removeItem((Venda) mvVendaBox.getSelectedItem());
        changePanel(telaMainVendedor);
    }//GEN-LAST:event_evExcluirVendaActionPerformed

    private void evOkEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evOkEditarActionPerformed
        ItemVenda iv = (ItemVenda) evItemVendaBox.getSelectedItem();
        evQuantidadeEditar.setText(String.valueOf(iv.getQuantidade()));

    }//GEN-LAST:event_evOkEditarActionPerformed

    private void evSalvarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evSalvarItemActionPerformed
        vendas.get(mvVendaBox.getSelectedIndex()).getProdutos().get(evItemVendaBox.getSelectedIndex()).setQuantidade(Integer.parseInt(evQuantidadeEditar.getText()));
        inj.exportarVenda(vendas);
    }//GEN-LAST:event_evSalvarItemActionPerformed

    private void evSalvarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evSalvarVendaActionPerformed
        try {
            vendas.get(mvVendaBox.getSelectedIndex()).setDataPagamento(DataUtil.StringParaData(evDataPagamento.getText()));
            vendas.get(mvVendaBox.getSelectedIndex()).setDataVencimento(DataUtil.StringParaData(evDataVencimento.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        inj.exportarVenda(vendas);
    }//GEN-LAST:event_evSalvarVendaActionPerformed

    private void evVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evVoltarActionPerformed
        changePanel(telaMainVendedor);
    }//GEN-LAST:event_evVoltarActionPerformed

    private void cVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cVoltarActionPerformed
        changePanel(telaCadastroCliente);
    }//GEN-LAST:event_cVoltarActionPerformed

    private void cIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cIrActionPerformed
        if (cCodigo.getText().equals(String.valueOf(randomNum))) {
            Cliente c = new Cliente();
            c.setID(Integer.parseInt(ccId.getText()));
            c.setNome(ccNome.getText());
            c.setSenha(Encription.sha1(new String(ccSenha.getPassword())));
            c.setUsuario(ccUsuario.getText());
            c.setBairro(ccBairro.getText());
            c.setCidade(ccCidade.getText());
            c.setCpf(ccCPF.getText());
            c.setEmail(ccEmail.getText());
            c.setEndereco(ccEndereco.getText());
            c.setEstado(ccEstado.getText());
            c.setFone(ccFone.getText());
            c.setNumero(Integer.parseInt(ccNumero.getText()));
            c.setRg(ccRG.getText());
            clientes.add(c);
            inj.exportarCliente(clientes);
            cError.setText("Cliente cadastrado!");
            cError.setForeground(Color.GREEN);
            cError.setVisible(true);
            try {
                Thread.sleep(5000);
            } catch (InterruptedException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
            changePanel(telaLogin);
        } else {
            cError.setVisible(true);
        }

    }//GEN-LAST:event_cIrActionPerformed

    private void evExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evExcluirItemActionPerformed
        ItemVenda iv = (ItemVenda) evItemVendaBox.getSelectedItem();
        vendas.get(mvVendaBox.getSelectedIndex()).getProdutos().remove(iv);
        inj.exportarVenda(vendas);
    }//GEN-LAST:event_evExcluirItemActionPerformed

    private void mvSincronizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvSincronizarActionPerformed
        Sincronizacao s = new Sincronizacao();
        s.sincronizar();
    }//GEN-LAST:event_mvSincronizarActionPerformed

    private void mcComprasBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcComprasBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcComprasBoxActionPerformed

    private void mcVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcVoltarActionPerformed
        changePanel(telaLogin);
    }//GEN-LAST:event_mcVoltarActionPerformed

    private void mvSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvSairActionPerformed
        changePanel(telaLogin);
    }//GEN-LAST:event_mvSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cCodigo;
    private javax.swing.JLabel cError;
    private javax.swing.JButton cIr;
    private javax.swing.JButton cVoltar;
    private javax.swing.JTextField ccBairro;
    private javax.swing.JTextField ccCPF;
    private javax.swing.JButton ccCadastrar;
    private javax.swing.JTextField ccCidade;
    private javax.swing.JTextField ccEmail;
    private javax.swing.JTextField ccEndereco;
    private javax.swing.JLabel ccError;
    private javax.swing.JTextField ccEstado;
    private javax.swing.JTextField ccFone;
    private javax.swing.JTextField ccId;
    private javax.swing.JTextField ccNome;
    private javax.swing.JTextField ccNumero;
    private javax.swing.JTextField ccRG;
    private javax.swing.JPasswordField ccSenha;
    private javax.swing.JTextField ccUsuario;
    private javax.swing.JButton ccVoltar;
    private javax.swing.JButton cpCadastrar;
    private javax.swing.JTextField cpDescricao;
    private javax.swing.JLabel cpError;
    private javax.swing.JTextField cpEstoque;
    private javax.swing.JTextField cpId;
    private javax.swing.JTextField cpValor;
    private javax.swing.JButton cpVoltar;
    private javax.swing.JButton cvCadastrar;
    private javax.swing.JTextField cvEmail;
    private javax.swing.JLabel cvError;
    private javax.swing.JTextField cvId;
    private javax.swing.JTextField cvNome;
    private javax.swing.JPasswordField cvSenha;
    private javax.swing.JTextField cvUsuario;
    private javax.swing.JButton cvVoltar;
    private javax.swing.JComboBox<Produto> evAddItemBox;
    private javax.swing.JTextField evDataPagamento;
    private javax.swing.JTextField evDataVencimento;
    private javax.swing.JButton evExcluirItem;
    private javax.swing.JButton evExcluirVenda;
    private javax.swing.JComboBox<ItemVenda> evItemVendaBox;
    private javax.swing.JButton evOkAddItem;
    private javax.swing.JButton evOkEditar;
    private javax.swing.JTextField evQuantidadeAddItem;
    private javax.swing.JTextField evQuantidadeEditar;
    private javax.swing.JButton evSalvarItem;
    private javax.swing.JButton evSalvarVenda;
    private javax.swing.JButton evVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton lCadastrar;
    private javax.swing.JRadioButton lCliente;
    private javax.swing.JLabel lError;
    private javax.swing.JRadioButton lJSON;
    private javax.swing.JButton lLogin;
    private javax.swing.JPasswordField lSenha;
    private javax.swing.JTextField lUsuario;
    private javax.swing.JRadioButton lVendedor;
    private javax.swing.JRadioButton lXML;
    private javax.swing.JComboBox<Venda> mcComprasBox;
    private javax.swing.JButton mcOk;
    private javax.swing.JScrollPane mcScrollPanel;
    private javax.swing.JTable mcTable;
    private javax.swing.JButton mcVoltar;
    private javax.swing.JButton mvCadastrarProduto;
    private javax.swing.JButton mvCriarVenda;
    private javax.swing.JLabel mvEditarVenda;
    private javax.swing.JButton mvSair;
    private javax.swing.JButton mvSelecionaVenda;
    private javax.swing.JLabel mvSelectProduct;
    private javax.swing.JButton mvSincronizar;
    private javax.swing.JComboBox<Venda> mvVendaBox;
    private javax.swing.JPanel painelPai;
    private javax.swing.JComboBox<Cliente> rvClientBox;
    private javax.swing.JTextField rvDataPagamento;
    private javax.swing.JTextField rvDataVencimento;
    private javax.swing.JButton rvFinalizarCompra;
    private javax.swing.JTextField rvID;
    private javax.swing.JButton rvOkProduct;
    private javax.swing.JComboBox<Produto> rvProductBox;
    private javax.swing.JTextField rvQtd;
    private javax.swing.JLabel rvSelectClient;
    private javax.swing.JLabel rvValorItem;
    private javax.swing.JLabel rvValorVenda;
    private javax.swing.JButton rvVoltar;
    private javax.swing.JPanel telaCadastroCliente;
    private javax.swing.JPanel telaCadastroProduto;
    private javax.swing.JPanel telaCadastroVendedor;
    private javax.swing.JPanel telaCodigo;
    private javax.swing.JPanel telaEditaVenda;
    private javax.swing.JPanel telaLogin;
    private javax.swing.JPanel telaMainCliente;
    private javax.swing.JPanel telaMainVendedor;
    private javax.swing.JPanel telaRealizaVenda;
    private javax.swing.ButtonGroup tipoPersistencia;
    private javax.swing.ButtonGroup tipoUsuario;
    // End of variables declaration//GEN-END:variables
}
